apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
      - name: express-api
        image: your-docker-registry/express-api:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongodb-uri

---
apiVersion: v1
kind: Service
metadata:
  name: express-api
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: express-api-nodeport
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000
  type: NodePort

